### ISSUE TITLE
Not working in iOS

### ISSUE THREAD

**Issue by jonathanfds** [JC-Chris/XFExtensions#2]
Hi there,
I tryed use it in iOS, but it is freezing the view,  anything in view works.
I downloaded the sample and I updated the packages and the same result was happen.
Sorry my bad english 😄

**Comment by DennisWelu** [comment]
Same experience with the ZoomImage control - image displays but does not respond to anything. I pulled in ImageZoom.cs and the iOS ImageZoomRenderer directly to my project and it works fine.

**Comment by jonathanfds** [comment]
Yeah, I pulled too, but to work I had remove the async tasks in the renderer.

**Comment by chrispy2day** [comment]
Hi all, sorry for the delay in responding.  With the holiday and day job, haven't had a lot of extra time.  The controls haven't been updated in a while, but I've started on an update to bring them inline with the latest packages.  I haven't started on the ZoomImage control yet, but I'll take a look the weekend.  However, note that with the recent updates to Xamarin.Forms, you can handle the zoom directly in XF.  I am planning on doing some performance testing to see if I should continue to maintain my control or deprecate it.

**Comment by chrispy2day** [comment]
Hi all, I just pushed some new updates into a XamFormsUpdate branch.  Give that a try and see how it works for you.  I just did some quick tests on Android and iOS and didn't have a problem, but certainly wasn't extensive enough to be conclusive.

The main issue that I was seeing was the Fody.PropertyChanged that I was using to weave in the INotifyPropertyChanged stopped working for some reason so I replaced that with a manual implementation.  However, there have been a ton of changes pending since the last stable release, so something in there could have caused the issues you were seeing.  In any case, hopefully fixed now!

I have some more updates and testing to do across all the controls, but I'll try and get a new stable release out here and on NuGet ASAP (probably should update to the new-fangled standard NuGet versioning too).  I'll likely not get anything done this week (double booked across two different clients so long hours at the day job), but next week things should slow down and I can focus more energy to this.

Anyway, thanks for using the components and let me know how the project updates work for you!

**Comment by erhardsmit** [comment]
Hi. Was the issues on iOS fixed because I just pulled the latest branch source and still not getting expected results?

**Comment by jonathanfds** [comment]
Sorry I can't test this right now, because I'm without my MAC, when I test I'll send the result here.
Thanks

**Comment by DennisWelu** [comment]
@erhardsmit Just to double check - are you using the XamFormsUpdate branch?

**Comment by chrispy2day** [comment]
@erhardsmit Yes, when I last updated the XamFormsUpdate branch, I wasn't having any issues on either iOS or Android.  Like @DennisWelu said, double check that you're on the XamFormsUpdate and not the master branch.  If you're still having an issue let me know.  Thanks!

**Comment by Nixon-Joseph** [comment]
I found an issue in the code that may be the issue you're experiencing.

In the IOS `ZoomImageRenderer` on line 78, it can throw an exception if the uri isn't perfectly formatted. (including spaces - [see here](https://bugzilla.xamarin.com/show_bug.cgi?id=29510)). What I did is replace the part on line 77 where it's `var url = webSource.Uri.ToString()` with `var url = webSource.Uri.AbsoluteUri`. Because the `AbsoluteUri` property has the full uri string with escaped characters (including space).

I don't know for sure if this will work with images that require query params, but for me, the issue was a space in the image filename, causing `NSUrl.FromString(url)` to return null, thereby throwing an exception. I know for a fact that I'll never care about query params, so this fix is good for me.
